spring:
  datasource:
    username: ghernandez
    password: Alsea.001
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.245.2:1433;databaseName=MercadoFoods
  jooq:
    sql-dialect: org.hibernate.dialect.SQLServer2008Dialect
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    hibernate:
      ddl-auto: none

